name: Generate Contribution Snake Game Animation

on:
  schedule:
    # Run every 24 hours at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generates a snake game from a github user contribution grid
      - name: Generate github-user-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: amriflh
          outputs: |
            assets/github-user-contribution-grid-snake.svg?color_snake=#10B981&color_dots=#09150E,#0F2619,#064E3B,#059669,#34D399
            assets/github-user-contribution-grid-snake-dark.svg?color_snake=#34D399&color_dots=#09150E,#062E22,#047857,#10B981,#6EE7B7

      - name: Commit & Push Assets
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update contribution snake animation [skip ci]"
          file_pattern: "assets/*.svg"
