name: Generate Contribution Snake Animation
on:
schedule:
- cron: "0 0 1-31 1-12 0-6"
workflow_dispatch:
push:
branches:
- main
- master
jobs:
generate:
permissions:
contents: write
runs-on: ubuntu-latest
timeout-minutes: 5
steps:
- name: Checkout Repository
uses: actions/checkout@v4
- name: Generate github user contribution grid snake
uses: Platane/snk/svg-only@v3
with:
github_user_name: amriflh
outputs: assets/github-user-contribution-grid-snake.svg
- name: Commit and Push Assets
uses: stefanzweifel/git-auto-commit-action@v5
with:
commit_message: "update contribution snake animation"
file_pattern: "assets/github-user-contribution-grid-snake.svg"
